# Generated by Django 2.2.5 on 2022-08-02 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220801_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='tag',
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(choices=[('writer', 'Writers'), ('reader', 'Reader'), ('admin', 'Admin')], default='reader', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('w', 'در انتظار تایید'), ('d', 'تایید شده')], default='w', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='main.Tag'),
        ),
        migrations.DeleteModel(
            name='CategoryManaging',
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
        migrations.AddField(
            model_name='preference',
            name='post',
            field=models.ForeignKey(on_delete=True, to='main.Post'),
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('user', 'post', 'value')},
        ),
    ]
