# Generated by Django 2.2.5 on 2022-08-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220802_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(choices=[('reader', 'Reader'), ('admin', 'Admin'), ('writer', 'Writers')], default='reader', max_length=10),
        ),
    ]
